### ISSUE TITLE
能不能设置一个快捷键弹出翻译界面？

### ISSUE THREAD

**Issue by yulelong** [wallenweel/weel-translation-extension#11]
有几个建议，不知实现起来方便不：
1、网页中翻译快捷键
比如选中单词的时候（或者之后），按下某个按键就能弹出翻译的窗口。选中任何单词都弹出小按钮是很方便，但是也是一种干扰，因为有时候只是极个别的词不认识，更多的时候双击选中单词只是为了复制......
2、工具栏翻译界面
目前是ctrl+enter的方式翻译，可否加各设置改成输完就翻译呢，或者回车就翻译。这种翻译换行的作用不是很常用吧。（或者有其他方面的考虑？）
3、工具栏上的图标不太美好啊~~

**Comment by wallenweel** [comment]
弹窗因为新的扩展 api 没有提供相关功能，故没有办法实现，针对干扰的情况提供了两种方式，长按浮动按钮2秒消失后刷新前不再显示 和 右键菜单翻译；

热键的话没有考虑太多，只是顺手按自己习惯加了一个，也没怎么用过，因为面板是鼠标触发的，也就直接点击翻译了；

图标没有沿用第一版的或者重新设计是因为只想把这个做成小工具，风格按照 MD 设计所以就直接用了官方的图标；

Ps：近期在进行漫画相关的学习活动不怎么接触开发了，时间和精力都不太够，对于频繁调整接口更新迭代以及超长审核周期的火狐有些累觉不爱，等新的接口区域全面稳定后计划重构一遍 😂
