### ISSUE TITLE
设置交互方式时，如果不使用浮动按钮，右键翻译不会弹出浮动面板

### ISSUE THREAD

**Issue by childepeng** [wallenweel/weel-translation-extension#16]
设置交互方式时，如果不使用浮动按钮，右键翻译不会弹出浮动面板

**Comment by wallenweel** [comment]
有可能是翻译源网络延迟或不通，如果使用 `com 谷歌` 的话尝试切换 `cn` 或其它翻译源；
问题依旧的话，提供下有问题的链接 (╹ڡ╹ )

**Comment by childepeng** [comment]
卸载了重新安装后，就好了
