### ISSUE TITLE
选中中文时能否不要弹出悬浮图标

### ISSUE THREAD

**Issue by ivysrono** [wallenweel/weel-translation-extension#8]
既然是为墙内用户做的，那么需要以中文为源语言就是个极为小众的需求，最好能加个选项，减少干扰。

**Comment by wallenweel** [comment]
我英语词汇量一般，所以常常会需要查中文的英译，因此才在主面板添加了 “快速切换” 语言的功能，如果仅仅将中文作为目标语言那就成了 “中文翻译器” 了。
不过，之后会考虑添加屏蔽非源语言的特性，只对当前选作源的语言类型响应活动。

**Comment by ivysrono** [comment]
需要翻译扩展的词汇量都一般ε=ε=ε=┏(゜ロ゜;)┛
我的想法是，中文用户到底看中文多，鼠标点点选选在所难免，弹出太多很干扰，不如给个选项，屏蔽特定语言的浮动按钮。
所以我要的时黑名单模式，屏蔽中文。至于有没有人要白名单模式，仅翻译特定语言时弹出炫富按钮……大概比较少吧。

ps我知道针对墙内的意思不是只针对中文，应该是使用了 translate.google.cn 的意思，毕竟 .com 至今还是不能用。我只是说墙内主要是中文用户，可以考虑针对中文做一些特别优化。

**Comment by wallenweel** [comment]
过滤规则么，感觉用在一个翻译扩展上有点奇怪，而且这个扩展总共也就支持三个语言。
只是为了不让悬浮按钮出现，目前已经给出了三种方式：**只用右键菜单、长按按钮 2 秒临时隐藏、popup 面板设置关闭**。

前阵子 translate.google.com 回归大陆可以用了，所以暂停一些特性的开发，因为有更好的扩展，只是最近又不能访问了。

放到 1.0 版本的开发计划里了，实现上没什么问题。

**Comment by ivysrono** [comment]
我之前是用重定向扩展强行将 translate.google.com 重定向到 .cn ，但是其他扩展还是不那么满意就是因为没找到你这么好用的悬浮按钮。

**Comment by wallenweel** [comment]
已在审核中的 v0.2.8 版本中添加，但实现的比较初级，默认是关闭的可在 菜单 - 设置 中开启

**Comment by wallenweel** [comment]
已通过审核 ;D
