### ISSUE TITLE
为什么我查日文单词点击发音后却是中文发音？

### ISSUE THREAD

**Issue by summerist999** [wallenweel/weel-translation-extension#9]
如题。如果没有中文对应发音的话就没有声音（比如假名，或日文自造字）

请教如何解决，谢谢！

**Comment by wallenweel** [comment]
当前发音是直接使用浏览器的 TTS （Text To Speach）引擎，很少用发音，只测试了中英，没注意日语不发音。。
查了一些资料，应该是浏览器只支持中英朗读的缘故，第三方发音服务只找到了谷歌的，但必须翻墙才能用；有时间添加个选项使用翻译源的发音好了，原本打算尽可能不依赖网络服务的。

**Comment by summerist999** [comment]
好的谢谢！另外希望能在浏览器附加组件页面也加入选项按钮方便设置。

**Comment by wallenweel** [comment]
翻译源语音朗读已接入，等待审核发布；
附加组件的选项和翻译面板的菜单设置基本是一样的实现方式，所以不打算在正式版本重复写一遍（设置存储都是用的 storage 接口），不然以后每次改动都要写两份 XD；

**Comment by summerist999** [comment]
THANX AGAIN.

**Comment by wallenweel** [comment]
该版本已通过审核（其他语音朗读注意选择正确的语言），关闭 issue ;D
